name: squirrels
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - pandas=2.2.2
  - altair=5.3.0
  - vegafusion=1.6.9
  - vl-convert-python=1.9.0
  - jupyterlab=4.2.5
  - shiny=1.2.1
  - folium=0.20.0
  - geopandas=1.1.2
  - matplotlib=3.10.8
  - plotly=6.5.2
  - pip=26.0.1
  - pip:
      - shinywidgets==0.3.4
  
